# Generated by Django 4.2.20 on 2025-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.CharField(max_length=6)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('university', models.BooleanField()),
                ('graduate', models.BooleanField()),
                ('employed', models.BooleanField()),
                ('job_seeker', models.BooleanField()),
                ('welfare_receipient', models.BooleanField()),
                ('parents_own_house', models.BooleanField()),
                ('disability_in_family', models.BooleanField()),
                ('subscription_account', models.IntegerField()),
                ('total_assets', models.BigIntegerField()),
                ('car_value', models.BigIntegerField()),
                ('income_range', models.CharField(choices=[('100% 이하', '100% 이하'), ('50% 이하', '50% 이하')], max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
