# Generated by Django 4.2.20 on 2025-06-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_is_eligible_profile_priority_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_eligible',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='priority_info',
        ),
    ]
