# Generated by Django 4.2.20 on 2025-11-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_is_eligible_profile_priority_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_married',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='residence',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
