# Generated by Django 4.2.20 on 2025-12-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_is_married_profile_residence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='eligibility_status',
            field=models.CharField(choices=[('idle', '대기'), ('running', '분석중'), ('done', '완료'), ('error', '실패')], default='idle', max_length=20),
        ),
    ]
