# Generated by Django 4.2.20 on 2026-01-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_eligibility_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_married',
            field=models.CharField(blank=True, choices=[('single', '미혼'), ('new', '신혼부부'), ('married', '기혼')], max_length=10, null=True),
        ),
    ]
