# Generated by Django 4.2.20 on 2025-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('posted_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', '모집예정'), ('open', '모집중'), ('closed', '모집마감')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
