# Generated by Django 4.2.20 on 2025-05-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('posted_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', '모집예정'), ('open', '모집중'), ('closed', '모집마감')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('total_households', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_households', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('house_type', models.CharField(blank=True, max_length=100, null=True)),
                ('elevator', models.CharField(blank=True, max_length=100, null=True)),
                ('parking', models.TextField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_info_list', to='announcements.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('schedule', '모집 일정'), ('criteria', '지원 자격'), ('housing_info', '주택 정보'), ('precautions', '유의 사항'), ('priority_score', '가점사항 및 점수'), ('residence_period', '거주 기간')], max_length=20)),
                ('data_file', models.FileField(upload_to='announcements/%(doc_type)s/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='announcements.announcement')),
            ],
            options={
                'unique_together': {('announcement', 'doc_type')},
            },
        ),
    ]
