# Generated by Django 4.2.20 on 2025-05-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_date', models.DateField(help_text='모집공고일 (예: 2025-01-01)')),
                ('online_application_period', models.JSONField(blank=True, default=dict, help_text="인터넷 신청접수 기간: {'start': 날짜, 'end': 날짜}")),
                ('inspection_period', models.JSONField(blank=True, default=dict, help_text="입주자격 검증 기간: {'start': 날짜, 'end': 날짜")),
                ('winner_announcement', models.DateTimeField(blank=True, help_text="당첨자 발표 일시 (예: '2022-08-17' 또는 '2022-08-17T17:00:00')", null=True)),
                ('contract_period', models.JSONField(blank=True, default=dict, help_text="계약 기간: {'start': 날짜|null, 'end': 날짜|null}")),
                ('payment_period', models.JSONField(blank=True, default=dict, help_text="납부 기간: {'start': 날짜|null, 'end': 날짜|null}")),
                ('move_in_period', models.JSONField(blank=True, default=dict, help_text="입주 기간: {'start': 'YYYY-MM' or 날짜, 'end': 'YYYY-MM' or 날짜}")),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='announcements.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='ResidencePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="거주기간 설명 (예: '2년 단위로 재계약이 가능하되, 4회를 초과할 수 없습니다.')")),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residence_period', to='announcements.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='PriorityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_criteria', models.JSONField(blank=True, default=list, help_text='우선순위별 조건 리스트')),
                ('score_items', models.JSONField(blank=True, default=list, help_text='가점 항목별 점수 리스트')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_score', to='announcements.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Precaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='본 정보는 AI를 활용하여 요약되었으며, 정확성이 보장되지 않을 수 있으므로 참고용으로만 사용하시기 바랍니다. 더 자세한 정보는 아래의 첨부파일을 참고하세요.', help_text='AI 유의사항 설명')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precaution', to='announcements.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='주택 이름', max_length=100)),
                ('address', models.CharField(help_text='주택 주소', max_length=255)),
                ('total_households', models.PositiveIntegerField(blank=True, help_text='총 세대 수', null=True)),
                ('supply_households', models.PositiveIntegerField(help_text='공급 세대 수')),
                ('type', models.CharField(blank=True, help_text='주택 유형', max_length=50, null=True)),
                ('house_type', models.CharField(blank=True, help_text='주택형', max_length=50, null=True)),
                ('elevator', models.BooleanField(default=False, help_text='엘리베이터 설치 여부')),
                ('parking', models.CharField(blank=True, help_text='주차 정보', max_length=50, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_info', to='announcements.announcement')),
            ],
        ),
    ]
