# Generated by Django 4.2.20 on 2025-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinginfo',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
