# Generated by Django 4.2.20 on 2025-05-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
