# Generated by Django 4.2.20 on 2025-05-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_schedule_residenceperiod_priorityscore_precaution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precaution',
            name='message',
        ),
        migrations.AddField(
            model_name='precaution',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text="유의사항 리스트 (예: ['첫 번째 유의사항', '두 번째 유의사항'])"),
        ),
        migrations.AlterField(
            model_name='precaution',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precautions', to='announcements.announcement'),
        ),
        migrations.CreateModel(
            name='AIPrecaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='본 정보는 AI를 활용하여 요약되었으며, 정확성이 보장되지 않을 수 있으므로 참고용으로만 사용하시기 바랍니다. 더 자세한 정보는 아래의 첨부파일을 참고하세요.', help_text='AI 유의사항 설명')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_precaution', to='announcements.announcement')),
            ],
        ),
    ]
