# Generated by Django 4.2.20 on 2025-05-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_housinginfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinginfo',
            name='house_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housinginfo',
            name='supply_households',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housinginfo',
            name='total_households',
            field=models.TextField(blank=True, null=True),
        ),
    ]
