# Generated by Django 4.2.20 on 2025-05-27 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_pdf_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_households', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_households', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('house_type', models.CharField(blank=True, max_length=100, null=True)),
                ('elevator', models.CharField(blank=True, max_length=100, null=True)),
                ('parking', models.TextField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_info_list', to='announcements.announcement')),
            ],
            options={
                'unique_together': {('announcement', 'external_id')},
            },
        ),
    ]
