# Generated by Django 4.2.20 on 2025-06-01 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0003_alter_housinginfo_house_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingEligibilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=False)),
                ('priority', models.CharField(max_length=50)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_analyses', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'announcement'], name='announcemen_user_id_b113b2_idx'), models.Index(fields=['is_eligible'], name='announcemen_is_elig_623d6a_idx'), models.Index(fields=['priority'], name='announcemen_priorit_433721_idx')],
                'unique_together': {('user', 'announcement')},
            },
        ),
    ]
