# Generated by Django 4.2.20 on 2025-05-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_housinginfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='housinginfo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='housinginfo',
            name='external_id',
        ),
    ]
