# Generated by Django 4.2.20 on 2025-06-01 10:35

import announcements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_housingeligibilityanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementdocument',
            name='data_file',
            field=models.FileField(upload_to=announcements.models.get_upload_path),
        ),
    ]
