# Generated by Django 4.2.20 on 2025-06-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_announcementdocument_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingeligibilityanalysis',
            name='reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='housingeligibilityanalysis',
            name='priority',
            field=models.CharField(default='', max_length=100),
        ),
    ]
