# Generated by Django 4.2.20 on 2025-11-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_housingeligibilityanalysis_reasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='ai_summary_json',
            field=models.JSONField(blank=True, help_text='AI가 PDF에서 추출한 요약 JSON 데이터', null=True),
        ),
        migrations.DeleteModel(
            name='AnnouncementDocument',
        ),
    ]
