# Generated by Django 4.2.20 on 2025-11-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_announcement_ai_summary_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='posted_date',
            new_name='announcement_date',
        ),
    ]
