# Generated by Django 4.2.20 on 2025-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_rename_posted_date_announcement_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
