# Generated by Django 4.2.20 on 2025-11-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_alter_announcement_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinginfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
