# Generated by Django 4.2.20 on 2025-12-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_alter_housinginfo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housinginfo',
            name='house_type',
        ),
        migrations.RemoveField(
            model_name='housinginfo',
            name='supply_households',
        ),
        migrations.AlterField(
            model_name='housinginfo',
            name='elevator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
