# Generated by Django 4.2.20 on 2025-12-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0011_remove_housinginfo_house_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housinginfo',
            name='house_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housinginfo',
            name='supply_households',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housinginfo',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
    ]
