# Generated by Django 4.2.20 on 2025-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_housinginfo_house_type_housinginfo_supply_households_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinginfo',
            name='type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
