# Generated by Django 4.2.20 on 2025-12-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0013_fix_housinginfo_type_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinginfo',
            name='type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
